### ISSUE TITLE
有没有办法实现1customCDN.sh和EXTRA.SH在青龙执行ql update的时候自动更新

### ISSUE THREAD

**Issue by synoman** [OreosLab/VIP#4]
RT，目前都是运行命令：`docker exec -it QL bash -c "$(curl -fsSL https://raw.githubusercontents.com/Oreomeow/VIP/main/Scripts/sh/1customCDN.sh)"`，然后再逐项输入选择，然后重新在配置文件里面把TG BOT的TOKEN和其他一些选项手动逐一更改

**Comment by ghost** [comment]
@synoman 配置不多的话可以定制一个自动更新放 extra.sh 里面

**Comment by synoman** [comment]
谢谢大佬，不会代码，学习了一下你的代码，试了一下失败了

**Comment by ghost** [comment]
[Update.sh](https://raw.githubusercontent.com/Oreomeow/VIP/main/Scripts/sh/Update.sh)
给了几个参数，自己改下

**Comment by synoman** [comment]
感谢大佬
