### ISSUE TITLE
code里看得到自己活动助力码，但是没有进行内部助力

### ISSUE THREAD

**Issue by Pessimisticc** [OreosLab/VIP#6]
code里看得到活动助力码，但是没有进行内部助力，而是给作者助力请问大佬是怎么回事，如何解决！^_^

**Comment by Pessimisticc** [comment]
因为用的是是最新task_before.sh,改回到# Build 20210817-001后正常

**Comment by ghost** [comment]
@yuanlang1 青龙没有更新到新版的（具体不知道哪个版本），回退 20210817-001 版本的 task_before.sh 即可
